### ISSUE TITLE
Tag check box does not remove tag

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#15] opened 2017-06-09 10:13 UTC
Clicking on a tag name will toggle the tag fine, but the check box only toggles one way (ie on)

**Comment by kansallisarkisto** [comment] 2017-06-12 04:25
I need to know more about reproducing this. For me it works perfectly in both Firefox and Chrome.

**Comment by hackmanschorsch** [comment] 2017-06-12 12:14
Have you tested on readTest or your development environment? I have tested on readTest and Firefox 53.0.3. So for the checkbox only selection is possible. Pressing once more clears the checkbox but not the tag line.

**Comment by kansallisarkisto** [comment] 2017-06-19 10:03
I've now tested readTest with the following:

Chromium: Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
Firefox: 53.0.3 (64-bit)

I can't reproduce the problem with either one of those browsers. Try again? Maybe it was an older version?

**Comment by hackmanschorsch** [comment] 2017-07-07 12:13
Problem persists on Firefox 54.0.1 (32-Bit). Easy fix would be to allow tag selection only on the text rather then the checkbox. But a smarter fix would be preferable.

**Comment by kansallisarkisto** [comment] 2017-07-27 13:04
I did some testing, the problem with removing tags only occurs if you open the tag menu and add a tag and then click to remove it without closing the tag menu in between. If you close the menu and open it again, it works fine. I will try to track this down, anyway.

**Closed as completed** 2017-08-14 10:35 UTC
