### ISSUE TITLE
"Correction Interface" should also act as a viewer with an "Edit" button

### ISSUE THREAD

**Issue by kansallisarkisto** [Transkribus/TWI-edit#17] opened 2017-06-16 11:21 UTC
"Correction Interface" should have an "Edit" button. The button should be grayed out when the document lacks a segmentation and thus cannot be transcribed. Clicking the button should instruct the user to create a segmentation for the document using the expert client.

**Comment by cziaarm** [comment] 2017-08-24 08:05
This looks to be done as a sort of duplicate of  Transkribus/TWI-mc#44 and Transkribus/TWI-edit#17

**Closed as completed** 2017-08-24 11:42 UTC
Labels: enhancement
