### ISSUE TITLE
Edit line box shows up too small

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-edit#47] opened 2017-08-29 07:57 UTC
I open the edit interface, then choose a line to transcribe, but get this:
![kuva](https://user-images.githubusercontent.com/16373538/29810202-b75024b6-8ca7-11e7-870e-94d628fe1141.png)

Happens both on Firefox and on Chrome, apparently when no transcriptions have been made on the page.

**Comment by kansallisarkisto** [comment] 2017-09-06 07:28
The width issue seems to be resolved when I rewrote things. Height is still a problem but I'm working on that.

**Comment by kansallisarkisto** [comment] 2017-09-06 11:37
The problem still persists in some cases, removing this label.

**Comment by kansallisarkisto** [comment] 2017-09-06 13:06
Both width and height should be ok now.

**Comment by cziaarm** [comment] 2017-09-11 19:49
I think there has been some regression as I closed Transkribus/TWI-edit#12 after confirming the example I reported was OK. I will close this one as I have opened Transkribus/TWI-edit#54 and assigned all the TWI-edit people to help deal with the regression issues.

**Closed as completed** 2017-09-11 19:49 UTC
Labels: bug
