### ISSUE TITLE
Edit box to follow the highlighted line

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#11] opened 2017-06-09 10:03 UTC
When clicking about on the image the edit box should move to stay relative to the clicked-on line.

**Comment by hackmanschorsch** [comment] 2017-07-21 13:08
duplicate of nr33 in TWI-mc

**Comment by cziaarm** [comment] 2017-08-11 12:14
duplicate of Transkribus/TWI-mc#33

**Closed as completed** 2017-08-18 14:29 UTC
Labels: enhancement
